---
- name: Install filebeat
  become: true
  dnf:
    name: "/tmp/filebeat-{{ filebeat_version }}-x86_64.rpm"
    state: present
    disablerepo: "appstream,baseos,epel,epel-modular,extras"
    disable_gpg_check: yes
  notify: restart filebeat